const $=s=>document.querySelector(s), api="api";
async function req(url,opt={}){let r=await fetch(api+"/"+url,opt);return r.json()}
async function boot(){let r=await req("auth.php?action=check");if(r.ok)showApp();else $("#loginView").classList.remove("hidden")}
function showApp(){$("#loginView").classList.add("hidden");$("#app").classList.remove("hidden");load("dashboard")}
$("#loginForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),r=await req("auth.php?action=login",{method:"POST",body:f});if(r.ok)showApp();else $("#loginMsg").textContent=r.message||"Login gagal"}
$("#logout").onclick=async()=>{await req("auth.php?action=logout");location.reload()}
document.querySelectorAll("aside button[data-page]").forEach(b=>b.onclick=()=>load(b.dataset.page));
function load(page){$("#pageTitle").textContent=page[0].toUpperCase()+page.slice(1);let c=$("#content");if(page==="dashboard")c.innerHTML=`<div class="panel"><h3>Dashboard</h3><p class="muted">Kelola konten Moonlight Event Equipment dari panel ini. Untuk production, koneksikan API ke MySQL dan simpan password dengan password_hash().</p></div><div class="grid"><div class="panel"><h3>Equipment</h3><p>Kelola katalog equipment.</p></div><div class="panel"><h3>Artikel</h3><p>Kelola artikel dan file.</p></div><div class="panel"><h3>Galeri</h3><p>Upload foto event.</p></div></div>`;
else if(page==="profile") formProfile();
else if(page==="settings") formSettings();
else if(page==="services"||page==="equipment"||page==="portfolio"||page==="articles"||page==="gallery") crud(page)}
function formProfile(){form("Profil Perusahaan",[["name","Nama Perusahaan","Moonlight Event Equipment"],["tagline","Tagline","Solusi Lengkap Sewa Alat Event Production"],["description","Deskripsi","Kami menyediakan berbagai kebutuhan event production untuk mendukung acara Anda agar tampil lebih profesional, maksimal, dan berkesan."],["vision","Visi","Menjadi partner event production terpercaya."],["mission","Misi","Menyediakan equipment berkualitas dan solusi teknis yang tepat."]])}
function formSettings(){form("Kontak & Pengaturan",[["whatsapp","WhatsApp","0896-3308-3344"],["whatsapp_link","Link WhatsApp","https://wa.me/+6289633083344"],["instagram","Instagram","@moonlight87962128"],["instagram_link","Instagram URL","https://www.instagram.com/moonlight87962128/"],["maps","Google Maps","https://maps.app.goo.gl/fPky2VQ5xe7SFRNG8?g_st=ac"],["seo_title","SEO Title","Moonlight Event Equipment | Sewa Event Production"]])}
function form(title,fields){$("#content").innerHTML=`<div class="panel"><h3>${title}</h3><form id="editForm" class="grid">${fields.map(x=>`<div class="field" style="${x[0]==="description"||x[0]==="vision"||x[0]==="mission"?"grid-column:1/-1":""}"><label>${x[1]}</label>${x[0].includes("description")||x[0]==="vision"||x[0]==="mission"?`<textarea name="${x[0]}">${x[2]}</textarea>`:`<input name="${x[0]}" value="${x[2]}">`}</div>`).join("")}<div style="grid-column:1/-1"><button class="save">Simpan Perubahan</button></div></form></div>`;$("#editForm").onsubmit=e=>{e.preventDefault();alert("Form siap dihubungkan ke endpoint API/MySQL.")}}
function crud(page){let labels={services:"Layanan",equipment:"Equipment",portfolio:"Portofolio",articles:"Artikel",gallery:"Galeri"};$("#content").innerHTML=`<div class="panel"><h3>Kelola ${labels[page]}</h3><p class="muted">Area CRUD dan upload device untuk ${labels[page]}. Endpoint API disediakan di folder <code>api/</code>.</p><input type="file" multiple><button class="save">Upload</button></div>`}
boot();